export const SET_PARAGRAPHS = 'SET_PARAGRAPHS';
export const SET_URL = 'SET_URL';
export const SET_SAVED_PARAGRAPHS = 'SET_SAVED_PARAGRAPHS';
export const DELETE_SAVED_PARAGRAPH = 'DELETE_SAVED_PARAGRAPH';
export const APPROVE_PARAGRAPH = 'APPROVE_PARAGRAPH';

