export const ADD_TERMINO = 'ADD_TERMINO';
export const SET_TERMINOS = 'SET_TERMINOS';
export const DELETE_TERMINO = 'DELETE_TERMINO';
export const EDIT_TERMINO = 'DELETE_TERMINO';


export const SET_PARAGRAPHS = 'SET_PARAGRAPHS';
export const SET_URL = 'SET_URL';
export const SET_SAVED_PARAGRAPHS = 'SET_SAVED_PARAGRAPHS';
export const DELETE_SAVED_PARAGRAPH = 'DELETE_SAVED_PARAGRAPH';
export const APPROVE_PARAGRAPH = 'APPROVE_PARAGRAPH';

